import {
  HRA_SPATIAL_UNITS,
  HRA_V11_ALLEN_BRAIN_ASSET,
  type HraCoordinateSpaceId,
} from "./HraSpatialReference";

export type AllenIcbm2009bCorrespondenceStatus = "unavailable";

export interface AllenAnnotationVolumeEvidence {
  filename: "annotation_full.nii.gz" | "annotation.nii.gz";
  sha256: string;
  sourceUrl: string;
  bytes: number;
  dimensions: readonly [394, 466, 378];
  voxelSpacingMillimetres: readonly [0.5, 0.5, 0.5];
  units: typeof HRA_SPATIAL_UNITS;
  affineSource: "qform";
  affine: readonly [
    readonly [0.5, 0, 0, -98],
    readonly [0, 0.5, 0, -134],
    readonly [0, 0, 0.5, -72],
    readonly [0, 0, 0, 1],
  ];
  orientationOfIncreasingVoxelIndices: readonly ["R", "A", "S"];
  originWorldMillimetres: readonly [-98, -134, -72];
  nonBackgroundLabelCount: 141;
  description: string;
}

export interface AllenStructureSemanticCandidate {
  glbNodeNames: readonly string[];
  allenAnnotationId: number;
  allenAcronym: string;
  allenName: string;
  laterality: "paired" | "midline";
  evidence: "exact-name-semantic-candidate";
  limitation: string;
}

export interface AllenIcbm2009bRegistrationEvidence {
  id: "luna-hra-allen-icbm-2009b-correspondence-v1";
  status: AllenIcbm2009bCorrespondenceStatus;
  sourceAsset: typeof HRA_V11_ALLEN_BRAIN_ASSET;
  sourceSpaceId: "luna-raw-hra-v11-allen-brain-glb";
  targetSpaceId: "allen-human-reference-atlas-3d-2020-icbm-2009b-sym";
  referenceDataset: {
    label: "Allen Human Reference Atlas – 3D, 2020";
    version: "1.0.0";
    referenceTemplate: "ICBM 2009b Nonlinear Symmetric";
    license: "CC BY 4.0";
    packageUrl: string;
    externalTemplate: {
      filename: "mni_icbm152_t1_tal_nlin_sym_09b_hires.nii";
      officialArchiveUrl: string;
      archiveApproximateSize: "348 MB";
      retrieved: false;
      reasonNotRetrieved: string;
    };
  };
  annotationVolumes: readonly AllenAnnotationVolumeEvidence[];
  semanticStructureCandidates: readonly AllenStructureSemanticCandidate[];
  transformArtifact: null;
  validation: {
    status: "unavailable";
    completedChecks: readonly string[];
    notCompletedChecks: readonly string[];
    landmarkResidualsMillimetres: null;
  };
  missingArtifacts: readonly string[];
  limitations: readonly string[];
  provenanceUrls: readonly string[];
  notExecutable: true;
}

const annotationBaseUrl =
  "https://download.alleninstitute.org/informatics-archive/allen_human_reference_atlas_3d_2020/version_1";

const sharedAnnotationEvidence = {
  sourceUrl: annotationBaseUrl,
  dimensions: [394, 466, 378] as const,
  voxelSpacingMillimetres: [0.5, 0.5, 0.5] as const,
  units: HRA_SPATIAL_UNITS,
  affineSource: "qform" as const,
  affine: [
    [0.5, 0, 0, -98],
    [0, 0.5, 0, -134],
    [0, 0, 0.5, -72],
    [0, 0, 0, 1],
  ] as const,
  orientationOfIncreasingVoxelIndices: ["R", "A", "S"] as const,
  originWorldMillimetres: [-98, -134, -72] as const,
  nonBackgroundLabelCount: 141 as const,
};

/**
 * The development-only inspection record is intentionally explicit about what
 * was measured from the official Allen package and what is still absent. It is
 * not a raw-GLB-to-ICBM transform and must never yield coordinates.
 */
export const ALLEN_ICBM_2009B_CORRESPONDENCE_EVIDENCE: AllenIcbm2009bRegistrationEvidence = {
  id: "luna-hra-allen-icbm-2009b-correspondence-v1",
  status: "unavailable",
  sourceAsset: HRA_V11_ALLEN_BRAIN_ASSET,
  sourceSpaceId: "luna-raw-hra-v11-allen-brain-glb",
  targetSpaceId: "allen-human-reference-atlas-3d-2020-icbm-2009b-sym",
  referenceDataset: {
    label: "Allen Human Reference Atlas – 3D, 2020",
    version: "1.0.0",
    referenceTemplate: "ICBM 2009b Nonlinear Symmetric",
    license: "CC BY 4.0",
    packageUrl: `${annotationBaseUrl}/`,
    externalTemplate: {
      filename: "mni_icbm152_t1_tal_nlin_sym_09b_hires.nii",
      officialArchiveUrl:
        "https://www.bic.mni.mcgill.ca/~vfonov/icbm/2009/mni_icbm152_nlin_sym_09b_nifti.zip",
      archiveApproximateSize: "348 MB",
      retrieved: false,
      reasonNotRetrieved:
        "The official Allen annotation header already establishes its image frame; the unresolved scientific issue is GLB-to-annotation provenance, which a template download cannot resolve.",
    },
  },
  annotationVolumes: [
    {
      ...sharedAnnotationEvidence,
      filename: "annotation_full.nii.gz",
      sha256:
        "2b05581e39c44f2623d9b0a69f64e3df0823c20d054abef92973812313335dc3",
      bytes: 1815762,
      description:
        "Official bilateral Allen annotation volume generated by the release's documented mirror workflow.",
    },
    {
      ...sharedAnnotationEvidence,
      filename: "annotation.nii.gz",
      sha256:
        "be23763c15386f2f211105f1e8144a6887e7615571229090e209b1c78355d378",
      bytes: 1117842,
      description:
        "Official original Allen annotation volume used by the release's documented mirror example.",
    },
  ],
  semanticStructureCandidates: [
    {
      glbNodeNames: [
        "Allen_head_of_hippocampus_L",
        "Allen_head_of_hippocampus_R",
      ],
      allenAnnotationId: 12171,
      allenAcronym: "HiH",
      allenName: "head of hippocampus",
      laterality: "paired",
      evidence: "exact-name-semantic-candidate",
      limitation:
        "The names align with the official Allen label table, but no GLB node-to-voxel-label or surface-generation artifact is published.",
    },
    {
      glbNodeNames: [
        "Allen_body_of_hippocampus_L",
        "Allen_body_of_hippocampus_R",
      ],
      allenAnnotationId: 12173,
      allenAcronym: "HiB",
      allenName: "body of hippocampus",
      laterality: "paired",
      evidence: "exact-name-semantic-candidate",
      limitation:
        "Semantic identity only; no vertex-to-voxel correspondence is available.",
    },
    {
      glbNodeNames: [
        "Allen_tail_of_hippocampus_L",
        "Allen_tail_of_hippocampus_R",
      ],
      allenAnnotationId: 12174,
      allenAcronym: "HiT",
      allenName: "tail of hippocampus",
      laterality: "paired",
      evidence: "exact-name-semantic-candidate",
      limitation:
        "Semantic identity only; no vertex-to-voxel correspondence is available.",
    },
    {
      glbNodeNames: [
        "Allen_head_of_caudate_L",
        "Allen_head_of_caudate_R",
      ],
      allenAnnotationId: 10335,
      allenAcronym: "CaH",
      allenName: "head of caudate",
      laterality: "paired",
      evidence: "exact-name-semantic-candidate",
      limitation:
        "Semantic identity only; no coordinate relation is supplied by either source.",
    },
    {
      glbNodeNames: ["Allen_putamen_L", "Allen_putamen_R"],
      allenAnnotationId: 10338,
      allenAcronym: "Pu",
      allenName: "putamen",
      laterality: "paired",
      evidence: "exact-name-semantic-candidate",
      limitation:
        "Semantic identity only; no coordinate relation is supplied by either source.",
    },
    {
      glbNodeNames: ["Allen_thalamus_L", "Allen_thalamus_R"],
      allenAnnotationId: 10390,
      allenAcronym: "THM",
      allenName: "thalamus",
      laterality: "paired",
      evidence: "exact-name-semantic-candidate",
      limitation:
        "Semantic identity only; no coordinate relation is supplied by either source.",
    },
    {
      glbNodeNames: [
        "Allen_paravermis_of_cerebellum_L",
        "Allen_paravermis_of_cerebellum_R",
      ],
      allenAnnotationId: 12384,
      allenAcronym: "CBPV",
      allenName: "paravermis of cerebellum",
      laterality: "paired",
      evidence: "exact-name-semantic-candidate",
      limitation:
        "Semantic identity only; no coordinate relation is supplied by either source.",
    },
    {
      glbNodeNames: ["Allen_corpus_callosum_L"],
      allenAnnotationId: 10561,
      allenAcronym: "cc",
      allenName: "corpus callosum",
      laterality: "midline",
      evidence: "exact-name-semantic-candidate",
      limitation:
        "The source names share the anatomical label but do not supply a mesh-to-label mapping or a midline landmark validation.",
    },
  ],
  transformArtifact: null,
  validation: {
    status: "unavailable",
    completedChecks: [
      "Exact raw GLB checksum identity to HRA v1.1 Allen_F_Brain.glb.",
      "Official Allen annotation NIfTI header inspection: dimensions, 0.5 mm spacing, qform affine, RAS orientation, millimetre units, origin, and 141 non-background label IDs.",
      "Official Allen scripts and HRA source-repository inspection for mesh generation or transform artifacts.",
      "Selected exact-name semantic candidates checked against official Allen graph-16 labels.",
    ],
    notCompletedChecks: [
      "GLB vertex-to-Allen-annotation voxel correspondence.",
      "Independent anatomical landmark pairs and residuals.",
      "Validated raw GLB-to-ICBM 2009b affine or deformation field.",
      "ICBM 2009b-to-2009c conversion.",
    ],
    landmarkResidualsMillimetres: null,
  },
  missingArtifacts: [
    "A versioned, checksum-bound Allen annotation input-to-HRA GLB/FBX mesh-generation artifact or per-vertex/voxel correspondence.",
    "A documented raw GLB-to-Allen/ICBM 2009b coordinate transform with declared axis conventions and units.",
    "Independent left/right, anterior/posterior, superior/inferior, scale, and landmark residual validation.",
  ],
  limitations: [
    "The HRA v1.1 graph placement is HRA reference-object evidence, not a GLB-to-Allen-volume mapping.",
    "Matching names, label counts, mirrored structure counts, raw geometry bounds, and visual similarity are insufficient to estimate a transform.",
    "This record does not make the Viewer presentation frame scientific and does not enable any lower-scale provider target.",
    "No 2009c registration is asserted or attempted.",
  ],
  provenanceUrls: [
    `${annotationBaseUrl}/`,
    "https://community.brain-map.org/t/allen-human-reference-atlas-3d-2020-new/405",
    "https://purl.humanatlas.io/ref-organ/brain-female/v1.1",
    "https://cdn.humanatlas.io/digital-objects/ref-organ/brain-female/v1.1/graph.json",
    "https://github.com/hubmapconsortium/hra-kg/tree/main/digital-objects/ref-organ/brain-female/v1.1/raw",
    "https://github.com/hubmapconsortium/ccf-3d-reference-object-library",
    "https://nist.mni.mcgill.ca/icbm-152-nonlinear-atlases-2009/",
  ],
  notExecutable: true,
};

export function getAllenIcbm2009bCorrespondenceEvidence(): AllenIcbm2009bRegistrationEvidence {
  return ALLEN_ICBM_2009B_CORRESPONDENCE_EVIDENCE;
}

export function isAllenIcbm2009bCoordinateSpace(
  spaceId: string,
): spaceId is HraCoordinateSpaceId {
  return spaceId === "allen-human-reference-atlas-3d-2020-icbm-2009b-sym";
}
