import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { BrainCircuit, Database, Trash2 } from "lucide-react";

export default function AgentMemory() {
  const utils = trpc.useUtils();
  const { data: memories = [], isLoading } = trpc.agent.memories.list.useQuery();
  const remove = trpc.agent.memories.remove.useMutation({ onSuccess: () => { utils.agent.memories.list.invalidate(); utils.agent.dashboard.invalidate(); } });
  return <div className="senota-page space-y-7"><section className="senota-hero-grid rounded-[1.75rem] border border-white/10 bg-card/70 p-7 sm:p-9"><div className="flex items-center gap-3 text-violet-300"><BrainCircuit className="size-5" /><span className="text-xs font-semibold uppercase tracking-[0.2em]">Persistent context</span></div><h1 className="mt-5 font-display text-4xl font-semibold tracking-[-0.045em] text-white">The useful things<br /><span className="text-white/45">it learns to keep.</span></h1><p className="mt-4 max-w-2xl text-sm leading-6 text-slate-400">Memories are factual project context and prior outcomes distilled after tasks complete. Remove anything that should not shape future reasoning.</p></section><section className="grid gap-4 lg:grid-cols-2">{isLoading ? <p className="text-sm text-slate-500">Loading memory…</p> : memories.length ? memories.map((memory) => <article key={memory.id} className="relative rounded-[1.5rem] border border-white/10 bg-card/70 p-5"><div className="flex items-start justify-between gap-4"><div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.16em] text-cyan-300"><Database className="size-3.5" /> {memory.category}</div><Button size="icon" variant="ghost" onClick={() => remove.mutate({ memoryId: memory.id })} className="size-8 text-slate-500 hover:bg-rose-400/10 hover:text-rose-300" aria-label="Remove memory"><Trash2 className="size-4" /></Button></div><p className="mt-4 whitespace-pre-wrap text-sm leading-6 text-slate-300">{memory.content}</p><div className="mt-5 flex items-center justify-between text-xs text-slate-600"><span>Importance {memory.importance}/5</span><span>{new Date(memory.updatedAt).toLocaleDateString()}</span></div></article>) : <div className="rounded-[1.5rem] border border-dashed border-white/10 p-10 text-center text-sm text-slate-500 lg:col-span-2">Complete a task to let SenotaAI retain its useful project context.</div>}</section></div>;
}
