import { AgentStatusBadge } from "@/components/AgentStatusBadge";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { BellRing, Bot, CalendarClock, CloudCog, Github, KeyRound, Save, ShieldCheck } from "lucide-react";
import { useEffect, useState } from "react";

function ConnectionRow({ label, connected, icon: Icon, detail }: { label: string; connected: boolean; icon: typeof Bot; detail: string }) {
  return <div className="flex items-center justify-between gap-4 rounded-2xl border border-white/10 bg-black/15 p-4"><div className="flex min-w-0 items-center gap-3"><div className={`grid size-9 place-items-center rounded-xl ${connected ? "bg-emerald-300/10 text-emerald-300" : "bg-white/5 text-slate-500"}`}><Icon className="size-4" /></div><div><p className="text-sm font-semibold text-slate-200">{label}</p><p className="mt-0.5 text-xs text-slate-500">{detail}</p></div></div><AgentStatusBadge status={connected ? "active" : "paused"} className="shrink-0" /></div>;
}

export default function Settings() {
  const utils = trpc.useUtils();
  const { data: settings } = trpc.agent.settings.get.useQuery();
  const { data: connections } = trpc.agent.connections.useQuery();
  const { data: schedules = [] } = trpc.agent.schedules.list.useQuery();
  const [form, setForm] = useState({ defaultModel: "", defaultExecutionMode: "confirm" as "confirm" | "auto", defaultMaxRetries: 2, githubRepository: "", vercelProject: "", notificationsEnabled: true });
  const [scheduleGoal, setScheduleGoal] = useState("");
  const [cron, setCron] = useState("0 0 9 * * 1");
  useEffect(() => { if (settings) setForm({ defaultModel: settings.defaultModel, defaultExecutionMode: settings.defaultExecutionMode, defaultMaxRetries: settings.defaultMaxRetries, githubRepository: settings.githubRepository, vercelProject: settings.vercelProject || "", notificationsEnabled: settings.notificationsEnabled }); }, [settings]);
  const update = trpc.agent.settings.update.useMutation({ onSuccess: () => { utils.agent.settings.get.invalidate(); utils.agent.dashboard.invalidate(); } });
  const createSchedule = trpc.agent.schedules.create.useMutation({ onSuccess: () => utils.agent.schedules.list.invalidate() });

  return <div className="senota-page space-y-7">
    <section><div className="mb-3 flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.2em] text-cyan-300"><CloudCog className="size-4" /> Agent settings</div><h1 className="font-display text-4xl font-semibold tracking-[-0.045em] text-white">Make the system yours.</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-400">Connection credentials remain server-side. These settings define where SenotaAI works and how much autonomy it receives.</p></section>
    <div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_360px]">
      <section className="space-y-6 rounded-[1.5rem] border border-white/10 bg-card/70 p-5 sm:p-7">
        <div><h2 className="text-lg font-semibold text-white">Execution defaults</h2><p className="mt-1 text-sm text-slate-500">Applied to every new task unless overridden.</p></div>
        <div className="grid gap-4 sm:grid-cols-2">
          <label className="text-xs font-semibold uppercase tracking-[0.14em] text-slate-500">Default model<input value={form.defaultModel} onChange={(e) => setForm({ ...form, defaultModel: e.target.value })} className="mt-2 h-11 w-full rounded-xl border border-white/10 bg-black/20 px-3 text-sm font-medium normal-case tracking-normal text-white outline-none focus:border-cyan-300/50" /></label>
          <label className="text-xs font-semibold uppercase tracking-[0.14em] text-slate-500">Retry budget<select value={form.defaultMaxRetries} onChange={(e) => setForm({ ...form, defaultMaxRetries: Number(e.target.value) })} className="mt-2 h-11 w-full rounded-xl border border-white/10 bg-black/20 px-3 text-sm font-medium normal-case tracking-normal text-white outline-none"><option value={0}>No retries</option><option value={1}>1 retry</option><option value={2}>2 retries</option></select></label>
          <label className="text-xs font-semibold uppercase tracking-[0.14em] text-slate-500">GitHub repository<input value={form.githubRepository} onChange={(e) => setForm({ ...form, githubRepository: e.target.value })} className="mt-2 h-11 w-full rounded-xl border border-white/10 bg-black/20 px-3 text-sm font-medium normal-case tracking-normal text-white outline-none focus:border-cyan-300/50" /></label>
          <label className="text-xs font-semibold uppercase tracking-[0.14em] text-slate-500">Vercel project ID<input value={form.vercelProject} onChange={(e) => setForm({ ...form, vercelProject: e.target.value })} placeholder="prj_..." className="mt-2 h-11 w-full rounded-xl border border-white/10 bg-black/20 px-3 text-sm font-medium normal-case tracking-normal text-white outline-none placeholder:text-slate-600 focus:border-cyan-300/50" /></label>
        </div>
        <div className="grid gap-3 sm:grid-cols-2">
          <button onClick={() => setForm({ ...form, defaultExecutionMode: "confirm" })} className={`rounded-2xl border p-4 text-left transition ${form.defaultExecutionMode === "confirm" ? "border-cyan-300/40 bg-cyan-300/[0.08]" : "border-white/10 bg-black/15"}`}><ShieldCheck className="size-5 text-cyan-300" /><p className="mt-3 text-sm font-semibold text-white">Confirm first</p><p className="mt-1 text-xs leading-5 text-slate-500">Reversible changes wait for you.</p></button>
          <button onClick={() => setForm({ ...form, defaultExecutionMode: "auto" })} className={`rounded-2xl border p-4 text-left transition ${form.defaultExecutionMode === "auto" ? "border-violet-300/40 bg-violet-300/[0.08]" : "border-white/10 bg-black/15"}`}><Bot className="size-5 text-violet-300" /><p className="mt-3 text-sm font-semibold text-white">Auto-run</p><p className="mt-1 text-xs leading-5 text-slate-500">Branch writes can proceed; destructive and production actions cannot.</p></button>
        </div>
        <button onClick={() => setForm({ ...form, notificationsEnabled: !form.notificationsEnabled })} className="flex w-full items-center justify-between rounded-xl border border-white/10 bg-black/15 px-4 py-3 text-left"><span className="flex items-center gap-3 text-sm font-medium text-slate-200"><BellRing className="size-4 text-amber-300" /> Owner notifications</span><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${form.notificationsEnabled ? "bg-emerald-300/10 text-emerald-300" : "bg-white/5 text-slate-500"}`}>{form.notificationsEnabled ? "On" : "Off"}</span></button>
        <div className="flex justify-end"><Button onClick={() => update.mutate({ ...form, vercelProject: form.vercelProject || null })} disabled={update.isPending} className="rounded-xl bg-cyan-300 text-slate-950 hover:bg-cyan-200"><Save className="mr-2 size-4" /> Save defaults</Button></div>
        {update.error && <p className="text-sm text-rose-300">{update.error.message}</p>}
      </section>
      <aside className="space-y-4"><div className="rounded-[1.5rem] border border-white/10 bg-card/70 p-5"><p className="mb-4 text-sm font-semibold text-white">Connection readiness</p><div className="space-y-3"><ConnectionRow label="Ollama-compatible brain" connected={Boolean(connections?.ollamaConfigured)} icon={Bot} detail="On-demand model endpoint" /><ConnectionRow label="GitHub workspace" connected={Boolean(connections?.githubConfigured)} icon={Github} detail="Repository tools and pull requests" /><ConnectionRow label="Vercel deployer" connected={Boolean(connections?.vercelConfigured)} icon={CloudCog} detail="Preview and production deployment API" /></div><div className="mt-4 flex gap-2 rounded-xl border border-white/10 bg-black/15 p-3 text-xs leading-5 text-slate-500"><KeyRound className="mt-0.5 size-4 shrink-0 text-slate-400" /> Add connection credentials using protected server-side configuration; they are never stored in browser settings.</div></div></aside>
    </div>
    <section className="rounded-[1.5rem] border border-white/10 bg-card/70 p-5 sm:p-7"><div className="flex items-center gap-2"><CalendarClock className="size-5 text-violet-300" /><div><h2 className="text-lg font-semibold text-white">Recurring tasks</h2><p className="mt-1 text-sm text-slate-500">Cron uses six UTC fields: seconds, minutes, hours, day, month, weekday.</p></div></div><div className="mt-5 grid gap-4 lg:grid-cols-[minmax(0,1fr)_180px_auto]"><input value={scheduleGoal} onChange={(e) => setScheduleGoal(e.target.value)} placeholder="Every Monday, audit the codebase and open a PR with focused improvements." className="h-11 rounded-xl border border-white/10 bg-black/20 px-3 text-sm text-white outline-none placeholder:text-slate-600" /><input value={cron} onChange={(e) => setCron(e.target.value)} className="h-11 rounded-xl border border-white/10 bg-black/20 px-3 font-mono text-sm text-cyan-100 outline-none" /><Button onClick={() => createSchedule.mutate({ goal: scheduleGoal, cronExpression: cron, model: form.defaultModel, executionMode: form.defaultExecutionMode })} disabled={scheduleGoal.trim().length < 12 || createSchedule.isPending} className="rounded-xl bg-violet-300 text-slate-950 hover:bg-violet-200">Add schedule</Button></div>{createSchedule.error && <p className="mt-3 text-sm text-rose-300">{createSchedule.error.message}</p>}<div className="mt-5 divide-y divide-white/5 rounded-xl border border-white/10">{schedules.length ? schedules.map((schedule) => <div key={schedule.id} className="flex flex-wrap items-center justify-between gap-3 p-4"><div><p className="text-sm font-medium text-slate-200">{schedule.goal}</p><p className="mt-1 font-mono text-xs text-slate-600">{schedule.cronExpression}</p><p className="mt-2 text-xs text-slate-500">{schedule.runs.length ? `${schedule.runs.length} stored run${schedule.runs.length === 1 ? "" : "s"} · latest ${schedule.runs[0]?.status.replaceAll("_", " ")}` : "No schedule runs recorded yet"}</p></div><AgentStatusBadge status={schedule.status} /></div>) : <div className="p-5 text-sm text-slate-500">No recurring tasks yet. Publish the dashboard before activating the first schedule.</div>}</div></section>
  </div>;
}
