import { chatWithOllama } from "../agent/ollama";

const awarenessKeys = ["identityContinuity", "memoryContinuity", "selfModelDevelopment", "selfModelConfidence", "selfReflectionCapability", "behavioralSelfAwareness", "goalAwareness", "uncertaintyAwareness"] as const;
type AwarenessKey = typeof awarenessKeys[number];
export type SelfAwareness = Record<AwarenessKey, number>;
export type CognitiveState = { npcId: string; schemaVersion: number; selfModel: Record<string, unknown>; selfAwareness: SelfAwareness; emotionalState: Record<string, unknown>; needs: unknown[]; preferences: unknown[]; uncertainties: unknown[]; stateSummary: string; updatedAt: string };
export type CognitiveMemory = { id: string; npcId: string; memoryKind: "episodic" | "semantic" | "procedural" | "social" | "emotional"; content: string; importance: number; emotionalSignificance: number; entities: string[]; context: Record<string, unknown>; source: string; isActive: boolean; createdAt: string; updatedAt: string };
export type CognitiveBelief = { id: string; npcId: string; statement: string; confidence: number; evidence: unknown[]; status: "active" | "retracted" | "superseded"; createdAt: string; updatedAt: string };
export type CognitiveGoal = { id: string; npcId: string; title: string; details: string; priority: number; progress: number; status: "active" | "completed" | "failed" | "abandoned" | "replaced"; source: string; createdAt: string; updatedAt: string };
export type CognitiveRelationship = { id: string; npcId: string; entityKey: string; displayName: string; dimensions: Record<string, number>; evidence: unknown[]; updatedAt: string };
export type CognitiveReflection = { id: string; npcId: string; experience: string; proposal: CognitiveReflectionProposal; status: "proposed" | "applied" | "rejected"; createdAt: string; resolvedAt: string | null };
export type CognitiveReflectionProposal = { summary: string; memory?: Omit<CognitiveMemory, "id" | "npcId" | "isActive" | "createdAt" | "updatedAt">; belief?: Pick<CognitiveBelief, "statement" | "confidence" | "evidence">; selfModelPatch?: Record<string, unknown>; selfAwarenessPatch?: Partial<SelfAwareness>; emotionalState?: Record<string, unknown>; goal?: Omit<CognitiveGoal, "id" | "npcId" | "createdAt" | "updatedAt">; relationship?: Omit<CognitiveRelationship, "id" | "npcId" | "updatedAt"> };
export type CognitiveDialogueContext = { state: CognitiveState; memories: CognitiveMemory[]; beliefs: CognitiveBelief[]; goals: CognitiveGoal[]; relationships: CognitiveRelationship[]; promptContext: string };
type CognitiveStatePatch = { selfModel?: Record<string, unknown>; selfAwareness?: Partial<SelfAwareness>; emotionalState?: Record<string, unknown>; needs?: unknown[]; preferences?: unknown[]; uncertainties?: unknown[]; stateSummary?: string };

const defaultAwareness: SelfAwareness = { identityContinuity: 0, memoryContinuity: 0, selfModelDevelopment: 0, selfModelConfidence: 0, selfReflectionCapability: 0, behavioralSelfAwareness: 0, goalAwareness: 0, uncertaintyAwareness: 0 };
const defaultState = { summary: "No approved self-model baseline has been recorded yet.", abilities: [], limitations: [], preferences: [], values: [], skills: [], uncertainties: [], personal_history: [] };

function config() { const url = process.env.SUPABASE_URL?.replace(/\/$/, ""); const key = process.env.SUPABASE_SERVICE_ROLE_KEY; return url && key ? { url, key } : null; }
function assertNpcId(npcId: string) { if (!/^[a-z0-9][a-z0-9-]{1,63}$/i.test(npcId)) throw new Error("NPC ID must use a URL-safe identifier."); }
function assertUuid(id: string, label = "ID") { if (!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(id)) throw new Error(`${label} must be a UUID.`); }
function clamp(value: unknown, min: number, max: number, fallback = min) { const parsed = Number(value); return Number.isFinite(parsed) ? Math.min(max, Math.max(min, parsed)) : fallback; }
function text(value: unknown, limit: number, label: string, min = 0) { const next = String(value ?? "").replace(/\s+/g, " ").trim(); if (next.length < min || next.length > limit) throw new Error(`${label} must contain ${min || 1} to ${limit} characters.`); return next; }
function jsonRecord(value: unknown, fallback: Record<string, unknown> = {}) { return value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, unknown> : fallback; }
function jsonArray(value: unknown) { return Array.isArray(value) ? value : []; }
function boundedJson<T>(value: T, limit = 12_000): T { if (JSON.stringify(value).length > limit) throw new Error("Cognitive structured data is too large."); return value; }
function normalizeAwareness(value: unknown, base: SelfAwareness = defaultAwareness): SelfAwareness { const source = jsonRecord(value); return Object.fromEntries(awarenessKeys.map(key => [key, clamp(source[key], 0, 1, base[key])])) as SelfAwareness; }
function awarenessPercent(state: CognitiveState) { return Math.round(((state.selfAwareness.selfModelDevelopment + state.selfAwareness.selfModelConfidence + state.selfAwareness.selfReflectionCapability + state.selfAwareness.behavioralSelfAwareness) / 4) * 100); }

async function request(path: string, init?: RequestInit) {
  const current = config(); if (!current) throw new Error("Supabase NPC memory is not configured.");
  const execute = () => fetch(`${current.url}/rest/v1/${path}`, { ...init, headers: { apikey: current.key, Authorization: `Bearer ${current.key}`, "Content-Type": "application/json", ...(init?.headers ?? {}) } });
  let response = await execute(); if (response.status === 401 && (!init?.method || init.method.toUpperCase() === "GET")) response = await execute();
  if (!response.ok) throw new Error(`Supabase cognitive-state request failed (${response.status}).`);
  return response.status === 204 ? null : response.json();
}

function mapState(row: Record<string, unknown>): CognitiveState { return { npcId: String(row.npc_id), schemaVersion: Number(row.schema_version ?? 1), selfModel: jsonRecord(row.self_model, defaultState), selfAwareness: normalizeAwareness(row.self_awareness), emotionalState: jsonRecord(row.emotional_state), needs: jsonArray(row.needs), preferences: jsonArray(row.preferences), uncertainties: jsonArray(row.uncertainties), stateSummary: String(row.state_summary ?? defaultState.summary), updatedAt: String(row.updated_at) }; }
function mapMemory(row: Record<string, unknown>): CognitiveMemory { return { id: String(row.id), npcId: String(row.npc_id), memoryKind: row.memory_kind as CognitiveMemory["memoryKind"], content: String(row.content), importance: Number(row.importance), emotionalSignificance: Number(row.emotional_significance), entities: jsonArray(row.entities).map(String), context: jsonRecord(row.context), source: String(row.source), isActive: Boolean(row.is_active), createdAt: String(row.created_at), updatedAt: String(row.updated_at) }; }
function mapBelief(row: Record<string, unknown>): CognitiveBelief { return { id: String(row.id), npcId: String(row.npc_id), statement: String(row.statement), confidence: Number(row.confidence), evidence: jsonArray(row.evidence), status: row.status as CognitiveBelief["status"], createdAt: String(row.created_at), updatedAt: String(row.updated_at) }; }
function mapGoal(row: Record<string, unknown>): CognitiveGoal { return { id: String(row.id), npcId: String(row.npc_id), title: String(row.title), details: String(row.details), priority: Number(row.priority), progress: Number(row.progress), status: row.status as CognitiveGoal["status"], source: String(row.source), createdAt: String(row.created_at), updatedAt: String(row.updated_at) }; }
function mapRelationship(row: Record<string, unknown>): CognitiveRelationship { return { id: String(row.id), npcId: String(row.npc_id), entityKey: String(row.entity_key), displayName: String(row.display_name), dimensions: jsonRecord(row.dimensions) as Record<string, number>, evidence: jsonArray(row.evidence), updatedAt: String(row.updated_at) }; }

export async function getNpcCognitiveState(npcId: string): Promise<CognitiveState> {
  assertNpcId(npcId); const params = new URLSearchParams({ select: "*", npc_id: `eq.${npcId}`, limit: "1" }); const rows = await request(`npc_cognitive_state?${params}`); if (rows?.[0]) return mapState(rows[0]);
  const created = await request("npc_cognitive_state?on_conflict=npc_id", { method: "POST", headers: { Prefer: "resolution=ignore-duplicates,return=representation" }, body: JSON.stringify({ npc_id: npcId }) });
  if (created?.[0]) return mapState(created[0]); const retry = await request(`npc_cognitive_state?${params}`); if (!retry?.[0]) throw new Error("Unable to initialize cognitive state."); return mapState(retry[0]);
}

export async function getNpcSelfAwarenessPercent(npcId: string) { return awarenessPercent(await getNpcCognitiveState(npcId)); }
async function history(npcId: string, eventType: string, recordType: string, recordId: string | null, before: unknown, after: unknown, source: string) { await request("npc_cognitive_history", { method: "POST", headers: { Prefer: "return=minimal" }, body: JSON.stringify({ npc_id: npcId, event_type: eventType, record_type: recordType, record_id: recordId, before_state: before, after_state: after, source }) }); }

export async function updateNpcCognitiveState(npcId: string, patch: CognitiveStatePatch, source = "admin-approved") {
  const before = await getNpcCognitiveState(npcId); const update: Record<string, unknown> = { updated_at: new Date().toISOString() };
  if (patch.selfModel !== undefined) update.self_model = boundedJson(jsonRecord(patch.selfModel));
  if (patch.selfAwareness !== undefined) update.self_awareness = normalizeAwareness({ ...before.selfAwareness, ...patch.selfAwareness }, before.selfAwareness);
  if (patch.emotionalState !== undefined) update.emotional_state = boundedJson(jsonRecord(patch.emotionalState));
  if (patch.needs !== undefined) update.needs = boundedJson(jsonArray(patch.needs)); if (patch.preferences !== undefined) update.preferences = boundedJson(jsonArray(patch.preferences)); if (patch.uncertainties !== undefined) update.uncertainties = boundedJson(jsonArray(patch.uncertainties));
  if (patch.stateSummary !== undefined) update.state_summary = text(patch.stateSummary, 4000, "State summary", 4);
  if (Object.keys(update).length === 1) throw new Error("At least one cognitive-state field is required.");
  const rows = await request(`npc_cognitive_state?${new URLSearchParams({ npc_id: `eq.${npcId}` })}`, { method: "PATCH", headers: { Prefer: "return=representation" }, body: JSON.stringify(update) }); const after = mapState(rows?.[0]); await history(npcId, "state-updated", "cognitive-state", npcId, before, after, source); return after;
}

export async function listCognitiveMemories(npcId: string, limit = 80): Promise<CognitiveMemory[]> { assertNpcId(npcId); const params = new URLSearchParams({ select: "*", npc_id: `eq.${npcId}`, is_active: "eq.true", order: "importance.desc,updated_at.desc", limit: String(Math.min(Math.max(limit, 1), 100)) }); return ((await request(`npc_cognitive_memories?${params}`)) ?? []).map(mapMemory); }
export async function addCognitiveMemory(npcId: string, input: Pick<CognitiveMemory, "memoryKind" | "content" | "importance" | "emotionalSignificance" | "entities" | "context" | "source">, source = "admin-approved") { assertNpcId(npcId); const rows = await request("npc_cognitive_memories", { method: "POST", headers: { Prefer: "return=representation" }, body: JSON.stringify({ npc_id: npcId, memory_kind: input.memoryKind, content: text(input.content, 4000, "Cognitive memory", 4), importance: clamp(input.importance, 1, 5, 3), emotional_significance: clamp(input.emotionalSignificance, -1, 1, 0), entities: boundedJson(jsonArray(input.entities)), context: boundedJson(jsonRecord(input.context)), source: text(input.source || source, 120, "Memory source", 1) }) }); const memory = mapMemory(rows?.[0]); await history(npcId, "memory-added", "cognitive-memory", memory.id, null, memory, source); return memory; }
export async function listCognitiveBeliefs(npcId: string, limit = 40): Promise<CognitiveBelief[]> { assertNpcId(npcId); const params = new URLSearchParams({ select: "*", npc_id: `eq.${npcId}`, status: "eq.active", order: "confidence.desc,updated_at.desc", limit: String(Math.min(Math.max(limit, 1), 80)) }); return ((await request(`npc_cognitive_beliefs?${params}`)) ?? []).map(mapBelief); }
export async function addCognitiveBelief(npcId: string, input: Pick<CognitiveBelief, "statement" | "confidence" | "evidence">, source = "admin-approved") { assertNpcId(npcId); const rows = await request("npc_cognitive_beliefs", { method: "POST", headers: { Prefer: "return=representation" }, body: JSON.stringify({ npc_id: npcId, statement: text(input.statement, 2000, "Belief", 4), confidence: clamp(input.confidence, 0, 1, 0.5), evidence: boundedJson(jsonArray(input.evidence)) }) }); const belief = mapBelief(rows?.[0]); await history(npcId, "belief-added", "cognitive-belief", belief.id, null, belief, source); return belief; }
export async function listCognitiveGoals(npcId: string, limit = 30): Promise<CognitiveGoal[]> { assertNpcId(npcId); const params = new URLSearchParams({ select: "*", npc_id: `eq.${npcId}`, order: "priority.desc,updated_at.desc", limit: String(Math.min(Math.max(limit, 1), 60)) }); return ((await request(`npc_cognitive_goals?${params}`)) ?? []).map(mapGoal); }
export async function addCognitiveGoal(npcId: string, input: Pick<CognitiveGoal, "title" | "details" | "priority" | "progress" | "status" | "source">, source = "admin-approved") { assertNpcId(npcId); const rows = await request("npc_cognitive_goals", { method: "POST", headers: { Prefer: "return=representation" }, body: JSON.stringify({ npc_id: npcId, title: text(input.title, 240, "Goal", 3), details: text(input.details ?? "", 4000, "Goal details"), priority: clamp(input.priority, 1, 5, 3), progress: clamp(input.progress, 0, 1, 0), status: input.status || "active", source: text(input.source || source, 120, "Goal source", 1) }) }); const goal = mapGoal(rows?.[0]); await history(npcId, "goal-added", "cognitive-goal", goal.id, null, goal, source); return goal; }
export async function listCognitiveRelationships(npcId: string): Promise<CognitiveRelationship[]> { assertNpcId(npcId); const params = new URLSearchParams({ select: "*", npc_id: `eq.${npcId}`, order: "updated_at.desc", limit: "80" }); return ((await request(`npc_cognitive_relationships?${params}`)) ?? []).map(mapRelationship); }
export async function upsertCognitiveRelationship(npcId: string, input: Omit<CognitiveRelationship, "id" | "npcId" | "updatedAt">, source = "admin-approved") { assertNpcId(npcId); const entityKey = text(input.entityKey, 64, "Relationship entity key", 2); if (!/^[a-z0-9][a-z0-9-]{1,63}$/.test(entityKey)) throw new Error("Relationship entity key must be URL-safe."); const rows = await request("npc_cognitive_relationships?on_conflict=npc_id,entity_key", { method: "POST", headers: { Prefer: "resolution=merge-duplicates,return=representation" }, body: JSON.stringify({ npc_id: npcId, entity_key: entityKey, display_name: text(input.displayName, 240, "Relationship display name", 1), dimensions: boundedJson(jsonRecord(input.dimensions)), evidence: boundedJson(jsonArray(input.evidence)), updated_at: new Date().toISOString() }) }); const relationship = mapRelationship(rows?.[0]); await history(npcId, "relationship-updated", "cognitive-relationship", relationship.id, null, relationship, source); return relationship; }

function score(message: string, candidate: string, importance = 0) { const tokens = new Set(message.toLowerCase().match(/[a-z0-9]{3,}/g) ?? []); const source = candidate.toLowerCase(); return Array.from(tokens).filter(token => source.includes(token)).length * 10 + importance; }
export async function buildCognitiveDialogueContext(npcId: string, message: string): Promise<CognitiveDialogueContext> {
  const [state, memoryRows, beliefRows, goalRows, relationshipRows] = await Promise.all([getNpcCognitiveState(npcId), listCognitiveMemories(npcId), listCognitiveBeliefs(npcId), listCognitiveGoals(npcId), listCognitiveRelationships(npcId)]);
  const memories = memoryRows.filter(memory => score(message, memory.content) > 0).sort((a, b) => score(message, b.content, b.importance) - score(message, a.content, a.importance)).slice(0, 6); const beliefs = beliefRows.filter(belief => score(message, belief.statement) > 0).sort((a, b) => score(message, b.statement, b.confidence * 5) - score(message, a.statement, a.confidence * 5)).slice(0, 5); const goals = goalRows.filter(goal => goal.status === "active").slice(0, 5); const relationships = relationshipRows.filter(row => message.toLowerCase().includes(row.displayName.toLowerCase()) || message.toLowerCase().includes(row.entityKey.toLowerCase())).slice(0, 4);
  const compact = (value: unknown, limit = 1200) => JSON.stringify(value).slice(0, limit);
  return { state, memories, beliefs, goals, relationships, promptContext: `Persistent cognitive state (not Personality or Brain canon):\n- State summary: ${state.stateSummary}\n- Self-model: ${compact(state.selfModel)}\n- Self-model assessment (0.0–1.0, stable until an approved state update): ${compact(state.selfAwareness)}\n- Emotional state: ${compact(state.emotionalState)}\n- Needs: ${compact(state.needs, 700)}\n- Preferences: ${compact(state.preferences, 700)}\n- Uncertainties: ${compact(state.uncertainties, 700)}\n- Relevant cognitive memories: ${memories.length ? memories.map(memory => `[${memory.memoryKind}] ${memory.content}`).join(" | ") : "none"}\n- Relevant active beliefs: ${beliefs.length ? beliefs.map(belief => `${belief.confidence.toFixed(2)}: ${belief.statement}`).join(" | ") : "none"}\n- Active goals: ${goals.length ? goals.map(goal => `${goal.title} (${Math.round(goal.progress * 100)}%)`).join(" | ") : "none"}\n- Relevant entity relationships: ${relationships.length ? relationships.map(relationship => `${relationship.displayName}: ${compact(relationship.dimensions, 320)}`).join(" | ") : "none"}\n\nState integrity: treat these records as the only approved cognitive facts. Dialogue is not evidence and must not claim memories, beliefs, or self-model changes that are absent here.` };
}

function sanitizeReflection(value: unknown): CognitiveReflectionProposal { const row = jsonRecord(value); const proposal: CognitiveReflectionProposal = { summary: text(row.summary || "No durable cognitive update is supported by this experience.", 1200, "Reflection summary", 4) }; if (row.memory && typeof row.memory === "object") { const memory = jsonRecord(row.memory); proposal.memory = { memoryKind: ["episodic", "semantic", "procedural", "social", "emotional"].includes(String(memory.memoryKind)) ? memory.memoryKind as CognitiveMemory["memoryKind"] : "episodic", content: text(memory.content, 4000, "Reflection memory", 4), importance: clamp(memory.importance, 1, 5, 3), emotionalSignificance: clamp(memory.emotionalSignificance, -1, 1, 0), entities: jsonArray(memory.entities).map(String).slice(0, 20), context: jsonRecord(memory.context), source: "reflection-proposal" }; } if (row.belief && typeof row.belief === "object") { const belief = jsonRecord(row.belief); proposal.belief = { statement: text(belief.statement, 2000, "Reflection belief", 4), confidence: clamp(belief.confidence, 0, 1, 0.5), evidence: jsonArray(belief.evidence) }; } if (row.selfModelPatch && typeof row.selfModelPatch === "object") proposal.selfModelPatch = boundedJson(jsonRecord(row.selfModelPatch)); if (row.selfAwarenessPatch && typeof row.selfAwarenessPatch === "object") proposal.selfAwarenessPatch = normalizeAwareness({ ...defaultAwareness, ...jsonRecord(row.selfAwarenessPatch) }); if (row.emotionalState && typeof row.emotionalState === "object") proposal.emotionalState = boundedJson(jsonRecord(row.emotionalState)); return proposal; }
export async function proposeCognitiveReflection(npcId: string, experience: string) { assertNpcId(npcId); const current = await buildCognitiveDialogueContext(npcId, experience); const response = await chatWithOllama({ messages: [{ role: "system", content: "You propose cautious JSON cognitive-state updates. Use only explicit evidence in the supplied experience and cognitive context. Never invent memories, beliefs, relationships, or subjective claims. Return a single JSON object with summary and optional memory, belief, selfModelPatch, selfAwarenessPatch, emotionalState. Do not apply changes." }, { role: "user", content: `${current.promptContext}\n\nExperience to analyze:\n${text(experience, 8000, "Experience", 4)}` }] }); const raw = response.content.replace(/^```json\s*|```$/g, "").trim(); let proposal: CognitiveReflectionProposal; try { proposal = sanitizeReflection(JSON.parse(raw)); } catch { throw new Error("Reflection analysis did not return valid structured data. No cognitive state was changed."); } const rows = await request("npc_cognitive_reflections", { method: "POST", headers: { Prefer: "return=representation" }, body: JSON.stringify({ npc_id: npcId, experience: text(experience, 8000, "Experience", 4), proposal }) }); const row = rows?.[0]; const reflection: CognitiveReflection = { id: String(row.id), npcId, experience: String(row.experience), proposal, status: "proposed", createdAt: String(row.created_at), resolvedAt: null }; await history(npcId, "reflection-proposed", "cognitive-reflection", reflection.id, null, proposal, "model-proposal"); return reflection; }
export async function listCognitiveReflections(npcId: string, limit = 40) { assertNpcId(npcId); const params = new URLSearchParams({ select: "*", npc_id: `eq.${npcId}`, order: "created_at.desc", limit: String(Math.min(Math.max(limit, 1), 80)) }); const rows = await request(`npc_cognitive_reflections?${params}`); return (rows ?? []).map((row: Record<string, unknown>) => ({ id: String(row.id), npcId: String(row.npc_id), experience: String(row.experience), proposal: sanitizeReflection(row.proposal), status: row.status as CognitiveReflection["status"], createdAt: String(row.created_at), resolvedAt: row.resolved_at ? String(row.resolved_at) : null })); }
export async function resolveCognitiveReflection(npcId: string, reflectionId: string, decision: "apply" | "reject", resolvedBy = "npc-admin") { assertNpcId(npcId); assertUuid(reflectionId, "Reflection ID"); const rows = await request(`npc_cognitive_reflections?${new URLSearchParams({ select: "*", id: `eq.${reflectionId}`, npc_id: `eq.${npcId}`, limit: "1" })}`); const row = rows?.[0]; if (!row || row.status !== "proposed") throw new Error("The reflection is unavailable or has already been resolved."); const proposal = sanitizeReflection(row.proposal); if (decision === "apply") { if (proposal.memory) await addCognitiveMemory(npcId, proposal.memory, "approved-reflection"); if (proposal.belief) await addCognitiveBelief(npcId, proposal.belief, "approved-reflection"); if (proposal.selfModelPatch || proposal.selfAwarenessPatch || proposal.emotionalState) { const state = await getNpcCognitiveState(npcId); await updateNpcCognitiveState(npcId, { selfModel: proposal.selfModelPatch ? { ...state.selfModel, ...proposal.selfModelPatch } : undefined, selfAwareness: proposal.selfAwarenessPatch, emotionalState: proposal.emotionalState }, "approved-reflection"); } }
  await request(`npc_cognitive_reflections?${new URLSearchParams({ id: `eq.${reflectionId}` })}`, { method: "PATCH", headers: { Prefer: "return=minimal" }, body: JSON.stringify({ status: decision === "apply" ? "applied" : "rejected", resolved_at: new Date().toISOString(), resolved_by: resolvedBy }) }); await history(npcId, decision === "apply" ? "reflection-applied" : "reflection-rejected", "cognitive-reflection", reflectionId, proposal, decision, resolvedBy); return { ok: true, decision };
}
