import type {
  ScientificLicenseRecord,
  ScientificProvenanceRecord,
} from "@shared/brainScience";

export const SCIENTIFIC_LICENSE_REGISTRY: ScientificLicenseRecord[] = [
  {
    id: "hra-brain-female-v1-1",
    provider: "HuBMAP / Human Reference Atlas",
    dataset: "HRA Brain-Female v1.1",
    license: "CC BY 4.0",
    redistribution: "permitted-with-attribution",
    sourceUrl: "https://purl.humanatlas.io/ref-organ/brain-female/v1.1",
    note: "Luna retains the visual GLB under the source record's attribution terms.",
  },
  {
    id: "julich-brain-v3-1",
    provider: "EBRAINS / Julich-Brain",
    dataset: "Julich-Brain Atlas cytoarchitectonic maps v3.1",
    license: "CC BY-NC-SA 4.0",
    redistribution: "not-redistributed",
    sourceUrl: "https://search.kg.ebrains.eu/instances/f1fe19e8-99bd-44bc-9616-a52850680777",
    note: "Luna requests lightweight provider metadata only and does not bundle Julich maps or meshes.",
  },
  {
    id: "bigbrain-provider-context",
    provider: "BigBrain / EBRAINS",
    dataset: "BigBrain provider context",
    license: "CC BY-NC-SA 4.0",
    redistribution: "not-redistributed",
    sourceUrl: "https://ftp.bigbrainproject.org/bigbrain-ftp/License.txt",
    note: "BigBrain is provider-scoped context only. Luna does not download, bundle, cache, stream, transform, or redistribute BigBrain assets; CC BY-NC-SA restrictions are retained for any future asset decision.",
  },
  {
    id: "allen-human-brain-atlas",
    provider: "Allen Institute",
    dataset: "Allen Human Brain Atlas",
    license: null,
    redistribution: "review-required",
    sourceUrl: "https://brain-map.org/support/documentation/human-brain-atlas-api",
    note: "Sample and donor metadata may be queried only under the provider's current terms; no raw dataset is bundled.",
  },
  {
    id: "siibra-spatial-backbone",
    provider: "EBRAINS / siibra",
    dataset: "MNI ICBM 152 2009c Nonlinear Asymmetric reference-space metadata",
    license: "Provider and source-template terms apply",
    redistribution: "not-redistributed",
    sourceUrl: "https://siibra-api-stable.apps.hbp.eu/v3_0/spaces?size=100",
    note: "Luna stores bounded reference-space metadata and makes server-side API requests only; no template, mesh, volume, or map is bundled.",
  },
  {
    id: "mni-icbm-152-2009c-template",
    provider: "MNI / EBRAINS siibra",
    dataset: "MNI ICBM 152 2009c Nonlinear Asymmetric template surface",
    license: "ICBM 152 Nonlinear atlases (2009) permission to use, copy, modify, and distribute for any purpose and without fee, with copyright notice retained.",
    redistribution: "permitted-with-attribution",
    sourceUrl: "https://jugit.fz-juelich.de/t.dickscheid/brainscapes-configurations/-/blob/siibra-0.4a86/spaces/icbm_152_2009c_nonl_asym.json",
    note: "Luna streams the two bounded provider-hosted cortical template fragments only after explicit user enablement. It does not bundle or persistently cache them, and retains source attribution.",
  },
  {
    id: "bigbrain-mni-transformations",
    provider: "EBRAINS hbp-spatial-backend",
    dataset: "Collection of transformations between Human Brain standard spaces, 2018 version",
    license: "CC BY-SA 4.0",
    redistribution: "not-redistributed",
    sourceUrl: "https://search.kg.ebrains.eu/instances/Dataset/7a9aa738-a5b2-4601-818e-05db2627ba5c",
    note: "Luna performs bounded remote coordinate queries only. It does not download, distribute, cache, execute, or expose deformation fields or transformed meshes.",
  },
  {
    id: "cellxgene-human-brain-atlas",
    provider: "CELLxGENE / Human Brain Cell Atlas",
    dataset: "Human Brain Cell Atlas collection metadata",
    license: null,
    redistribution: "review-required",
    sourceUrl: "https://api.cellxgene.cziscience.com/curation/v1/collections/283d65eb-dd53-496d-adb7-7570c7caa443",
    note: "Luna returns bounded provider metadata only and does not redistribute H5AD, cell coordinates, or raw expression files.",
  },
  {
    id: "hcp-provider-context",
    provider: "Human Connectome Project",
    dataset: "HCP connectivity provider context",
    license: null,
    redistribution: "review-required",
    sourceUrl: "https://www.humanconnectome.org/study/hcp-young-adult/document/hcp-young-adult-2025-release",
    note: "No HCP surface, CIFTI, connectivity matrix, or derivative is bundled by Luna.",
  },
];

export const SCIENTIFIC_PROVENANCE_REGISTRY: ScientificProvenanceRecord[] = [
  {
    id: "hra-brain-female-v1-1-graph",
    provider: "HuBMAP / Human Reference Atlas",
    dataset: "HRA Brain-Female v1.1 graph",
    version: "v1.1",
    sourceUrl: "https://cdn.humanatlas.io/digital-objects/ref-organ/brain-female/v1.1/graph.json",
    citation: "HRA Brain-Female v1.1",
    referenceSpaceId: null,
    registrationMethod: "Exact GLB mesh-node to HRA graph file_subpath identity join; not an MNI transform.",
    retrievedAt: "2026-08-26",
    evidenceTier: "structure-context",
    licenseId: "hra-brain-female-v1-1",
  },
  {
    id: "julich-brain-v3-1-mni-2009c",
    provider: "EBRAINS / Julich-Brain",
    dataset: "Julich-Brain Atlas cytoarchitectonic maps v3.1",
    version: "v3.1",
    sourceUrl: "https://search.kg.ebrains.eu/instances/f1fe19e8-99bd-44bc-9616-a52850680777",
    citation: "doi:10.25493/KNSN-XB4",
    referenceSpaceId: "ebrains-mni-icbm-152-2009c",
    registrationMethod: "Provider-native MNI ICBM 152 2009c nonlinear asymmetric atlas space; not a Luna transform.",
    retrievedAt: "2026-08-26",
    evidenceTier: "region-probabilistic",
    licenseId: "julich-brain-v3-1",
  },
  {
    id: "bigbrain-provider-context",
    provider: "BigBrain / EBRAINS",
    dataset: "BigBrain provider context",
    version: null,
    sourceUrl: "https://julich-brain-atlas.de/atlas",
    citation: null,
    referenceSpaceId: null,
    registrationMethod: null,
    retrievedAt: "2026-08-26",
    evidenceTier: "structure-context",
    licenseId: "bigbrain-provider-context",
  },
  {
    id: "allen-ahba-sample-context",
    provider: "Allen Institute",
    dataset: "Allen Human Brain Atlas sample context",
    version: null,
    sourceUrl: "https://brain-map.org/support/documentation/human-brain-atlas-api",
    citation: null,
    referenceSpaceId: null,
    registrationMethod: "Allen donor MR-to-MNI alignment applies to Allen donor/sample records only.",
    retrievedAt: "2026-08-26",
    evidenceTier: "structure-context",
    licenseId: "allen-human-brain-atlas",
  },
  {
    id: "siibra-spatial-backbone-mni-2009c",
    provider: "EBRAINS / siibra",
    dataset: "MNI ICBM 152 2009c Nonlinear Asymmetric provider reference space",
    version: "MNI 152 ICBM 2009c Nonlinear Asymmetric",
    sourceUrl: "https://siibra-api-stable.apps.hbp.eu/v3_0/spaces?size=100",
    citation: "Fonov VS, et al. ICBM 152 Nonlinear Atlases (2009).",
    referenceSpaceId: "ebrains-mni-icbm-152-2009c",
    registrationMethod: "Provider-native scientific reference space for explicit user-entered coordinate queries; not a Luna registration.",
    retrievedAt: "2026-08-26",
    evidenceTier: "point-validated",
    licenseId: "siibra-spatial-backbone",
  },
  {
    id: "siibra-mni-2009c-template-surface",
    provider: "EBRAINS / siibra",
    dataset: "MNI ICBM 152 2009c Nonlinear Asymmetric cortical template surface",
    version: "siibra-0.4a86 / 985dc194",
    sourceUrl: "https://siibra-api-stable.apps.hbp.eu/v3_0/spaces/minds/core/referencespace/v1.0.0/dafcffc5-4826-4bf1-8ff6-46b8a31ff8e2",
    citation: "Fonov VS, et al. ICBM 152 Nonlinear Atlases (2009).",
    referenceSpaceId: "ebrains-mni-icbm-152-2009c",
    registrationMethod: "Provider-native Neuroglancer legacy cortical template surface in MNI ICBM 152 2009c Nonlinear Asymmetric; not an HRA/Luna transform.",
    retrievedAt: "2026-08-26",
    evidenceTier: "structure-context",
    licenseId: "mni-icbm-152-2009c-template",
  },
  {
    id: "bigbrain-mni-2009c-transform-service",
    provider: "EBRAINS hbp-spatial-backend",
    dataset: "Collection of transformations between Human Brain standard spaces, 2018 version",
    version: "v1",
    sourceUrl: "https://hbp-spatial-backend.apps.hbp.eu/openapi.json",
    citation: "doi:10.25493/GA3Y-9V8",
    referenceSpaceId: "ebrains-bigbrain",
    registrationMethod: "Provider-documented diffeomorphic MNI ICBM 152 2009c Nonlinear Asymmetric to BigBrain 2015 histology coordinate transformation; not an HRA/Luna transform.",
    retrievedAt: "2026-08-26",
    evidenceTier: "point-validated",
    licenseId: "bigbrain-mni-transformations",
  },
  {
    id: "siibra-connectivity-provider-context",
    provider: "EBRAINS / siibra",
    dataset: "Parcellation-averaged connectivity feature context",
    version: "siibra configuration dependent",
    sourceUrl: "https://siibra-python.readthedocs.io/en/latest/examples/03_data_features/006_connectivity_matrices.html",
    citation: "siibra connectivity feature documentation.",
    referenceSpaceId: "ebrains-mni-icbm-152-2009c",
    registrationMethod: "Provider feature-to-parcellation association only; no HRA mesh relation is asserted.",
    retrievedAt: "2026-08-26",
    evidenceTier: "region-probabilistic",
    licenseId: "hcp-provider-context",
  },
  {
    id: "cellxgene-human-brain-sample-context",
    provider: "CELLxGENE / Human Brain Cell Atlas",
    dataset: "Human Brain Cell Atlas collection metadata",
    version: "Collection version retrieved at runtime",
    sourceUrl: "https://api.cellxgene.cziscience.com/curation/v1/collections/283d65eb-dd53-496d-adb7-7570c7caa443",
    citation: "Siletti K, et al. A cellular census of the human brain. Science. 2023.",
    referenceSpaceId: "cellxgene-human-brain-anatomical-annotation",
    registrationMethod: "Sample/dataset-scoped provider context; no whole-brain MNI or Luna mapping is asserted.",
    retrievedAt: "2026-08-26",
    evidenceTier: "structure-context",
    licenseId: "cellxgene-human-brain-atlas",
  },
  {
    id: "hcp-connectivity-provider-context",
    provider: "Human Connectome Project",
    dataset: "HCP connectivity provider context",
    version: "HCP-YA 2025",
    sourceUrl: "https://www.humanconnectome.org/study/hcp-young-adult/document/hcp-young-adult-2025-release",
    citation: null,
    referenceSpaceId: null,
    registrationMethod: "Provider-scoped HCP/fsLR and MNI-via-FNIRT context; no Luna mesh mapping is asserted.",
    retrievedAt: "2026-08-26",
    evidenceTier: "structure-context",
    licenseId: "hcp-provider-context",
  },
];

export function getScientificLicense(id: string) {
  return SCIENTIFIC_LICENSE_REGISTRY.find((record) => record.id === id) ?? null;
}

export function getScientificProvenance(id: string) {
  return SCIENTIFIC_PROVENANCE_REGISTRY.find((record) => record.id === id) ?? null;
}
