import type {
  MniScientificTemplateSurface,
  NormalizedScientificObservation,
  ScientificBrainArchitectureManifest,
  ScientificBrainLayer,
  ScientificCrosswalkRelationship,
} from "@shared/brainScience";
import {
  BRAIN_REFERENCE_SPACES,
} from "./registry";

export const MNI_SCIENTIFIC_TEMPLATE_SURFACE: MniScientificTemplateSurface = {
  id: "siibra-mni-2009c-cortical-template",
  label: "MNI ICBM 152 2009c Nonlinear Asymmetric cortical template",
  status: "PARTIAL",
  referenceSpaceId: "ebrains-mni-icbm-152-2009c",
  providerReferenceSpaceId: "minds/core/referencespace/v1.0.0/dafcffc5-4826-4bf1-8ff6-46b8a31ff8e2",
  configurationRevision: "siibra-0.4a86 / 985dc194",
  sourceUrl: "https://siibra-api-stable.apps.hbp.eu/v3_0/spaces/minds/core/referencespace/v1.0.0/dafcffc5-4826-4bf1-8ff6-46b8a31ff8e2",
  meshLabelIndex: 65535,
  format: "neuroglancer-legacy-precomputed-mesh",
  transformUrl: "https://neuroglancer.humanbrainproject.eu/precomputed/icbm152_2009c_nonlin_asym/transform.json",
  transformMatrixNanometres: [
    [1, 0, 0, -96500000],
    [0, 1, 0, -132500000],
    [0, 0, 1, -78500000],
    [0, 0, 0, 1],
  ],
  fragments: [
    {
      id: "left-hemisphere_cortex",
      url: "https://neuroglancer.humanbrainproject.eu/precomputed/icbm152_2009c_nonlin_asym/meshes/left-hemisphere_cortex",
      bytes: 1366303,
      decodedBytes: 2638432,
      etag: "\"65f4660a-14d91f\"",
      lastModified: "2024-03-15T15:15:22Z",
    },
    {
      id: "right-hemisphere_cortex",
      url: "https://neuroglancer.humanbrainproject.eu/precomputed/icbm152_2009c_nonlin_asym/meshes/right-hemisphere_cortex",
      bytes: 1386028,
      decodedBytes: 2673676,
      etag: "\"65f4660a-15262c\"",
      lastModified: "2024-03-15T15:15:22Z",
    },
  ],
  licensing: {
    license: "ICBM 152 Nonlinear atlases (2009): permission to use, copy, modify, and distribute for any purpose and without fee with the copyright notice retained.",
    redistribution: "permitted-with-attribution",
    attributionRequired: true,
    sourceUrl: "https://jugit.fz-juelich.de/t.dickscheid/brainscapes-configurations/-/blob/siibra-0.4a86/spaces/icbm_152_2009c_nonl_asym.json",
  },
  rendering: {
    defaultVisible: false,
    defaultOpacity: 0.48,
    deliveryMode: "provider-stream",
    cachePolicy: "no-persistent-cache",
    selectionCapability: "UNAVAILABLE_NO_REGION_LABELS",
  },
  limitation: "This is an exact provider-native MNI cortical template surface only. It supplies neither subcortical geometry nor Julich region labels, is never aligned to HRA, and cannot be selected as a provider region or Luna target.",
};

export const SCIENTIFIC_BRAIN_LAYERS: ScientificBrainLayer[] = [
  {
    id: "mni-scientific-template-surface",
    label: "MNI scientific cortical template",
    kind: "mni-template",
    status: "PARTIAL",
    referenceSpaceId: "ebrains-mni-icbm-152-2009c",
    defaultVisible: false,
    supportsOpacity: true,
    supportsRegionSelection: false,
    scientificTargetKind: null,
    provenanceId: "siibra-mni-2009c-template-surface",
    licenseId: "mni-icbm-152-2009c-template",
    limitation: MNI_SCIENTIFIC_TEMPLATE_SURFACE.limitation,
  },
  {
    id: "julich-cytoarchitecture",
    label: "Julich-Brain v3.1 probabilistic cytoarchitecture",
    kind: "tissue-atlas",
    status: "PARTIAL",
    referenceSpaceId: "ebrains-mni-icbm-152-2009c",
    defaultVisible: false,
    supportsOpacity: false,
    supportsRegionSelection: false,
    scientificTargetKind: "region-probabilistic-target",
    provenanceId: "julich-brain-v3-1-mni-2009c",
    licenseId: "julich-brain-v3-1",
    limitation: "MNI coordinate-to-region queries are provider-backed. The exact MNI Julich cortical mesh remains unresolved and is not rendered.",
  },
  {
    id: "bigbrain-coordinate-context",
    label: "BigBrain microscopic coordinate context",
    kind: "bigbrain-transform-context",
    status: "PARTIAL",
    referenceSpaceId: "ebrains-bigbrain",
    defaultVisible: false,
    supportsOpacity: false,
    supportsRegionSelection: false,
    scientificTargetKind: "scientific-coordinate-target",
    provenanceId: "bigbrain-mni-2009c-transform-service",
    licenseId: "bigbrain-mni-transformations",
    limitation: "Only independently entered MNI millimetre coordinates may be transformed through the documented provider service; no BigBrain image, layer mesh, raw volume, or HRA relation is rendered.",
  },
  {
    id: "bigbrain-microscopy",
    label: "BigBrain microscopy and cortical-layer assets",
    kind: "bigbrain-microscopy-context",
    status: "REQUIRES_REVIEW",
    referenceSpaceId: "ebrains-bigbrain",
    defaultVisible: false,
    supportsOpacity: false,
    supportsRegionSelection: false,
    scientificTargetKind: "structure-context-target",
    provenanceId: "bigbrain-provider-context",
    licenseId: "bigbrain-provider-context",
    limitation: "High-resolution microscopic assets are individual-brain data and are not loaded, cached, bundled, streamed, transformed, or redistributed by Luna.",
  },
  {
    id: "cellular-sample-context",
    label: "Cellular sample context",
    kind: "cellular-sample-context",
    status: "PARTIAL",
    referenceSpaceId: "cellxgene-human-brain-anatomical-annotation",
    defaultVisible: false,
    supportsOpacity: false,
    supportsRegionSelection: false,
    scientificTargetKind: "structure-context-target",
    provenanceId: "cellxgene-human-brain-sample-context",
    licenseId: "cellxgene-human-brain-atlas",
    limitation: "CELLxGENE collection metadata is sample-scoped anatomical/transcriptomic context; it is not a registered whole-brain coordinate layer.",
  },
  {
    id: "molecular-sample-context",
    label: "Molecular sample context",
    kind: "molecular-sample-context",
    status: "PARTIAL",
    referenceSpaceId: "allen-human-donor-mr",
    defaultVisible: false,
    supportsOpacity: false,
    supportsRegionSelection: false,
    scientificTargetKind: "point-validated-target",
    provenanceId: "allen-ahba-sample-context",
    licenseId: "allen-human-brain-atlas",
    limitation: "Allen donor/sample measurements remain donor- and sample-scoped. They are not inferred from Luna structure names or interpolated across the brain.",
  },
  {
    id: "connectivity-provider-context",
    label: "Provider-scoped connectivity context",
    kind: "connectivity-context",
    status: "PARTIAL",
    referenceSpaceId: "ebrains-mni-icbm-152-2009c",
    defaultVisible: false,
    supportsOpacity: false,
    supportsRegionSelection: false,
    scientificTargetKind: "region-probabilistic-target",
    provenanceId: "siibra-connectivity-provider-context",
    licenseId: "hcp-provider-context",
    limitation: "Connectivity is cohort-, parcellation-, method-, and provider-scoped. No edge, centroid, or region is mapped to HRA without explicit reviewed evidence.",
  },
];

export const SCIENTIFIC_BRAIN_BASELINE_OBSERVATIONS: NormalizedScientificObservation[] = [
  {
    id: "mni-template-surface-context",
    kind: "mni-template",
    status: "PARTIAL",
    provider: "EBRAINS / siibra",
    dataset: "MNI ICBM 152 2009c Nonlinear Asymmetric cortical template surface",
    version: MNI_SCIENTIFIC_TEMPLATE_SURFACE.configurationRevision,
    referenceSpaceId: "ebrains-mni-icbm-152-2009c",
    coordinate: null,
    region: null,
    mapId: null,
    measurement: { label: "Provider stream declaration", value: "2 cortical fragments", unit: "fragments", method: MNI_SCIENTIFIC_TEMPLATE_SURFACE.format },
    uncertainty: "Cortical-only template representation; no subcortical geometry or region labels.",
    provenanceId: "siibra-mni-2009c-template-surface",
    licenseId: "mni-icbm-152-2009c-template",
    retrievedAt: "2026-08-26",
    scientificTarget: null,
    limitation: MNI_SCIENTIFIC_TEMPLATE_SURFACE.limitation,
  },
  {
    id: "julich-v3-1-tissue-context",
    kind: "tissue-atlas",
    status: "PARTIAL",
    provider: "EBRAINS / Julich-Brain",
    dataset: "Julich-Brain Atlas cytoarchitectonic maps v3.1",
    version: "v3.1",
    referenceSpaceId: "ebrains-mni-icbm-152-2009c",
    coordinate: null,
    region: null,
    mapId: "siibra-map-v0.0.1_mni152-jba31-labelled",
    measurement: { label: "Provider MNI map catalog", value: "Labelled and probabilistic maps", unit: null, method: "Provider map metadata" },
    uncertainty: "Julich assignment is probabilistic and requires an independent MNI coordinate query.",
    provenanceId: "julich-brain-v3-1-mni-2009c",
    licenseId: "julich-brain-v3-1",
    retrievedAt: "2026-08-26",
    scientificTarget: null,
    limitation: "No HRA-to-Julich mapping and no exact MNI region-labelled cortical mesh are available in Luna.",
  },
  {
    id: "bigbrain-microscopy-context",
    kind: "bigbrain-microscopy-context",
    status: "REQUIRES_REVIEW",
    provider: "BigBrain / EBRAINS",
    dataset: "BigBrain 2015 release and cortical-layer assets",
    version: "2015 release",
    referenceSpaceId: "ebrains-bigbrain",
    coordinate: null,
    region: null,
    mapId: null,
    measurement: { label: "Microscopy delivery", value: "not loaded", unit: null, method: "License and delivery gate" },
    uncertainty: "Single postmortem-brain histological reference; raw image and layer assets are not represented as a whole-brain Luna layer.",
    provenanceId: "bigbrain-provider-context",
    licenseId: "bigbrain-provider-context",
    retrievedAt: "2026-08-26",
    scientificTarget: null,
    limitation: "No BigBrain asset is downloaded, cached, bundled, streamed, transformed, or redistributed by Luna.",
  },
  {
    id: "cellxgene-cellular-sample-context",
    kind: "cellular-sample-context",
    status: "PARTIAL",
    provider: "CELLxGENE / Human Brain Cell Atlas",
    dataset: "Human Brain Cell Atlas collection metadata",
    version: "runtime provider collection version",
    referenceSpaceId: "cellxgene-human-brain-anatomical-annotation",
    coordinate: null,
    region: null,
    mapId: null,
    measurement: { label: "Cellular coverage", value: "sample-scoped metadata", unit: null, method: "Provider collection query" },
    uncertainty: "Dataset and sample provenance remain required; collection metadata does not establish a whole-brain coordinate field.",
    provenanceId: "cellxgene-human-brain-sample-context",
    licenseId: "cellxgene-human-brain-atlas",
    retrievedAt: null,
    scientificTarget: null,
    limitation: "No Luna structure-to-dataset relation is inferred from display names, tissue labels, or titles.",
  },
  {
    id: "allen-molecular-sample-context",
    kind: "molecular-sample-context",
    status: "PARTIAL",
    provider: "Allen Institute",
    dataset: "Allen Human Brain Atlas microarray sample context",
    version: null,
    referenceSpaceId: "allen-human-donor-mr",
    coordinate: null,
    region: null,
    mapId: null,
    measurement: { label: "Molecular coverage", value: "donor/sample-scoped", unit: null, method: "Explicit provider sample or structure query" },
    uncertainty: "Allen donor/MR-to-MNI information applies to Allen records only and does not locate Luna geometry.",
    provenanceId: "allen-ahba-sample-context",
    licenseId: "allen-human-brain-atlas",
    retrievedAt: null,
    scientificTarget: null,
    limitation: "No molecular value is inferred from a Luna name, mesh position, or visual region.",
  },
  {
    id: "siibra-connectivity-context",
    kind: "connectivity-context",
    status: "PARTIAL",
    provider: "EBRAINS / siibra",
    dataset: "Parcellation-averaged connectivity feature context",
    version: "configuration dependent",
    referenceSpaceId: "ebrains-mni-icbm-152-2009c",
    coordinate: null,
    region: null,
    mapId: null,
    measurement: { label: "Connectivity scope", value: "provider/parcellation/cohort/method scoped", unit: null, method: "Provider connectivity feature" },
    uncertainty: "A matrix value requires a provider-declared feature, cohort, parcellation, modality, and endpoint relation.",
    provenanceId: "siibra-connectivity-provider-context",
    licenseId: "hcp-provider-context",
    retrievedAt: null,
    scientificTarget: null,
    limitation: "No connectivity edge, node, centroid, or region is projected onto HRA or Luna without reviewed provider evidence.",
  },
];

export const SCIENTIFIC_BRAIN_CROSSWALKS: ScientificCrosswalkRelationship[] = [
  {
    id: "hra-to-mni-2009c",
    source: { namespace: "hra", id: "hra-brain-female-v1-1", label: "HRA Brain-Female v1.1", referenceSpaceId: "hra-brain-female-v1-1" },
    target: { namespace: "ebrains", id: "ebrains-mni-icbm-152-2009c", label: "MNI ICBM 152 2009c Nonlinear Asymmetric", referenceSpaceId: "ebrains-mni-icbm-152-2009c" },
    relationshipType: "unmapped",
    status: "NOT_ESTABLISHED",
    provider: null,
    dataset: null,
    version: null,
    confidence: null,
    uncertainty: null,
    provenanceId: "hra-brain-female-v1-1-graph",
    licenseId: "hra-brain-female-v1-1",
    reviewStatus: "reviewed",
    limitation: "No source-published GLB-to-MNI transform artifact, mesh-to-volume correspondence, landmark residuals, or independent validation exists for the exact HRA asset.",
  },
  {
    id: "hra-to-julich-v3-1",
    source: { namespace: "hra", id: "hra-brain-female-v1-1", label: "HRA Brain-Female v1.1", referenceSpaceId: "hra-brain-female-v1-1" },
    target: { namespace: "julich", id: "minds/core/parcellationatlas/v1.0.0/94c1125b-b87e-45e4-901c-00daee7f2579-310", label: "Julich-Brain v3.1", referenceSpaceId: "ebrains-mni-icbm-152-2009c" },
    relationshipType: "unmapped",
    status: "UNMAPPED",
    provider: "EBRAINS / Julich-Brain",
    dataset: "Julich-Brain Atlas cytoarchitectonic maps v3.1",
    version: "v3.1",
    confidence: null,
    uncertainty: "No authoritative HRA-to-MNI relation exists from which a provider region relation could be evaluated.",
    provenanceId: "julich-brain-v3-1-mni-2009c",
    licenseId: "julich-brain-v3-1",
    reviewStatus: "reviewed",
    limitation: "No region relation is inferred from matching labels, UBERON identity, visual proximity, or MNI template juxtaposition.",
  },
  {
    id: "mni-2009c-to-bigbrain-2015",
    source: { namespace: "ebrains", id: "ebrains-mni-icbm-152-2009c", label: "MNI ICBM 152 2009c Nonlinear Asymmetric", referenceSpaceId: "ebrains-mni-icbm-152-2009c" },
    target: { namespace: "bigbrain", id: "ebrains-bigbrain", label: "BigBrain 2015 native histology", referenceSpaceId: "ebrains-bigbrain" },
    relationshipType: "coordinate-transform",
    status: "COMPLETE",
    provider: "EBRAINS hbp-spatial-backend",
    dataset: "Collection of transformations between Human Brain standard spaces, 2018 version",
    version: "v1",
    confidence: "Provider-documented diffeomorphic transformation; numerical reprojection error is provider/method dependent.",
    uncertainty: "Provider transformation is valid for its named template spaces only; it is not a Luna/HRA registration.",
    provenanceId: "bigbrain-mni-2009c-transform-service",
    licenseId: "bigbrain-mni-transformations",
    reviewStatus: "reviewed",
    limitation: "Only explicit MNI millimetre input may use the remote provider transform. It is not a Luna/HRA registration, and returned coordinates do not enable Luna navigation or a biological target.",
  },
];

export function getScientificBrainArchitectureManifest(): ScientificBrainArchitectureManifest {
  const scientificReferenceSpace = BRAIN_REFERENCE_SPACES.find((space) => space.id === "ebrains-mni-icbm-152-2009c");
  if (!scientificReferenceSpace) throw new Error("Canonical MNI reference space is not registered.");

  return {
    visualBrain: {
      model: "HRA Brain-Female v1.1",
      referenceSpaceId: "hra-brain-female-v1-1",
      status: "COMPLETE",
      lunaToMni: "NOT_ESTABLISHED",
    },
    scientificReferenceSpace,
    mniTemplateSurface: MNI_SCIENTIFIC_TEMPLATE_SURFACE,
    layers: SCIENTIFIC_BRAIN_LAYERS,
    observations: SCIENTIFIC_BRAIN_BASELINE_OBSERVATIONS,
    crosswalks: SCIENTIFIC_BRAIN_CROSSWALKS,
    limitations: [
      "HRA presentation coordinates and scientific MNI coordinates are separate evidence classes; Luna/HRA to MNI remains NOT_ESTABLISHED.",
      "The MNI template surface is an optional provider-streamed cortical reference, not a complete whole-brain mesh and not a Julich overlay.",
      "Julich assignments remain probabilistic and provider-defined; no HRA structure-to-Julich relation is inferred.",
      "BigBrain, cellular, molecular, and connectivity records retain their provider, sample, donor, cohort, parcellation, and reference-space scope.",
      "Only visual mesh targets remain Macro-simulation targets. Scientific context, coordinate, region, and point-validated targets do not grant lower-scale operations.",
    ],
  };
}
